version: "2"
services:
    app:
        container_name: app
        restart: always
        image: 217834298957.dkr.ecr.us-east-1.amazonaws.com/winniebot:latest
        ports:
        - "8080:8080"
        links:
        - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
        - ./data:/data/db
        ports:
        - "27017:27017"