version: "2"
services:
    app:
        container_name: app
        restart: always
        image: registry.hub.docker.com/lisushka/winnie_bot:latest
        ports:
        - "8080:8080"
        depends_on:
        # - mongo
        - postgres
    # mongo:
    #     container_name: mongo
    #     image: mongo
    #     restart: always
    #     volumes:
    #     - ./data:/data/db
    #     ports:
    #     - "27017:27017"
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        volumes:
        - ./postgres-data:/var/lib/postgresql/data
        # - ./sql/challenges.sql:/docker-entrypoint-initdb.d/challenges.sql
        - ./sql/config.sql:/docker-entrypoint-initdb.d/config.sql
        - ./sql/goals.sql:/docker-entrypoint-initdb.d/goals.sql
        - ./sql/raptors.sql:/docker-entrypoint-initdb.d/raptors.sql
        # - ./sql/totals.sql:/docker-entrypoint-initdb.d/totals.sql
        - ./sql/users.sql:/docker-entrypoint-initdb.d/users.sql
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_USER=dawn
        - POSTGRES_PASSWORD=1HH1Klad2bPP61yiEIwdB6
        - POSTGRES_DB=winnie_db